//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carEVA.Test.sidcarUserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSUsuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WSUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDOficinaActualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OficinaActualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionField;
        
        private byte TipoVinculacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroContratoField;
        
        private System.DateTime FechaInicioContratoField;
        
        private System.DateTime FechaFinContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        private int IDJefeInmediatoField;
        
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsngRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IDUsuario {
            get {
                return this.IDUsuarioField;
            }
            set {
                if ((this.IDUsuarioField.Equals(value) != true)) {
                    this.IDUsuarioField = value;
                    this.RaisePropertyChanged("IDUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IDOficinaActual {
            get {
                return this.IDOficinaActualField;
            }
            set {
                if ((object.ReferenceEquals(this.IDOficinaActualField, value) != true)) {
                    this.IDOficinaActualField = value;
                    this.RaisePropertyChanged("IDOficinaActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OficinaActual {
            get {
                return this.OficinaActualField;
            }
            set {
                if ((object.ReferenceEquals(this.OficinaActualField, value) != true)) {
                    this.OficinaActualField = value;
                    this.RaisePropertyChanged("OficinaActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string UsuarioCreacion {
            get {
                return this.UsuarioCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioCreacionField, value) != true)) {
                    this.UsuarioCreacionField = value;
                    this.RaisePropertyChanged("UsuarioCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Identificacion {
            get {
                return this.IdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionField, value) != true)) {
                    this.IdentificacionField = value;
                    this.RaisePropertyChanged("Identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public byte TipoVinculacion {
            get {
                return this.TipoVinculacionField;
            }
            set {
                if ((this.TipoVinculacionField.Equals(value) != true)) {
                    this.TipoVinculacionField = value;
                    this.RaisePropertyChanged("TipoVinculacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string NumeroContrato {
            get {
                return this.NumeroContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroContratoField, value) != true)) {
                    this.NumeroContratoField = value;
                    this.RaisePropertyChanged("NumeroContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime FechaInicioContrato {
            get {
                return this.FechaInicioContratoField;
            }
            set {
                if ((this.FechaInicioContratoField.Equals(value) != true)) {
                    this.FechaInicioContratoField = value;
                    this.RaisePropertyChanged("FechaInicioContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime FechaFinContrato {
            get {
                return this.FechaFinContratoField;
            }
            set {
                if ((this.FechaFinContratoField.Equals(value) != true)) {
                    this.FechaFinContratoField = value;
                    this.RaisePropertyChanged("FechaFinContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int IDJefeInmediato {
            get {
                return this.IDJefeInmediatoField;
            }
            set {
                if ((this.IDJefeInmediatoField.Equals(value) != true)) {
                    this.IDJefeInmediatoField = value;
                    this.RaisePropertyChanged("IDJefeInmediato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string MsngRespuesta {
            get {
                return this.MsngRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.MsngRespuestaField, value) != true)) {
                    this.MsngRespuestaField = value;
                    this.RaisePropertyChanged("MsngRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="sidcarUserServiceReference.WSIntegracionSoap")]
    public interface WSIntegracionSoap {
        
        // CODEGEN: Generating message contract since element name numeroRadicado from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerResumenRadicado", ReplyAction="*")]
        carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoResponse ObtenerResumenRadicado(carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerResumenRadicado", ReplyAction="*")]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoResponse> ObtenerResumenRadicadoAsync(carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoRequest request);
        
        // CODEGEN: Generating message contract since element name ObtenerResumenDocumentoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerResumenDocumento", ReplyAction="*")]
        carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoResponse ObtenerResumenDocumento(carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerResumenDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoResponse> ObtenerResumenDocumentoAsync(carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoRequest request);
        
        // CODEGEN: Generating message contract since element name idOrigenSistema from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AsociarRadicado", ReplyAction="*")]
        carEVA.Test.sidcarUserServiceReference.AsociarRadicadoResponse AsociarRadicado(carEVA.Test.sidcarUserServiceReference.AsociarRadicadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AsociarRadicado", ReplyAction="*")]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.AsociarRadicadoResponse> AsociarRadicadoAsync(carEVA.Test.sidcarUserServiceReference.AsociarRadicadoRequest request);
        
        // CODEGEN: Generating message contract since element name idOrigenSistema from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarRadicadoAsociado", ReplyAction="*")]
        carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoResponse EliminarRadicadoAsociado(carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarRadicadoAsociado", ReplyAction="*")]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoResponse> EliminarRadicadoAsociadoAsync(carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoRequest request);
        
        // CODEGEN: Generating message contract since element name idSistemaOrigen from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarDestinosDocumentoDigital", ReplyAction="*")]
        carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponse AgregarDestinosDocumentoDigital(carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarDestinosDocumentoDigital", ReplyAction="*")]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponse> AgregarDestinosDocumentoDigitalAsync(carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest request);
        
        // CODEGEN: Generating message contract since element name idSistemaOrigen from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarDestinosDocumentoDigital2", ReplyAction="*")]
        carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Response AgregarDestinosDocumentoDigital2(carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarDestinosDocumentoDigital2", ReplyAction="*")]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Response> AgregarDestinosDocumentoDigital2Async(carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignInJson", ReplyAction="*")]
        carEVA.Test.sidcarUserServiceReference.SignInJsonResponse SignInJson(carEVA.Test.sidcarUserServiceReference.SignInJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignInJson", ReplyAction="*")]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.SignInJsonResponse> SignInJsonAsync(carEVA.Test.sidcarUserServiceReference.SignInJsonRequest request);
        
        // CODEGEN: Generating message contract since element name ListaOficinasActivasResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaOficinasActivas", ReplyAction="*")]
        carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasResponse ListaOficinasActivas(carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaOficinasActivas", ReplyAction="*")]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasResponse> ListaOficinasActivasAsync(carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignIn", ReplyAction="*")]
        carEVA.Test.sidcarUserServiceReference.SignInResponse SignIn(carEVA.Test.sidcarUserServiceReference.SignInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignIn", ReplyAction="*")]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.SignInResponse> SignInAsync(carEVA.Test.sidcarUserServiceReference.SignInRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerResumenRadicadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerResumenRadicado", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoRequestBody Body;
        
        public ObtenerResumenRadicadoRequest() {
        }
        
        public ObtenerResumenRadicadoRequest(carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerResumenRadicadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroRadicado;
        
        public ObtenerResumenRadicadoRequestBody() {
        }
        
        public ObtenerResumenRadicadoRequestBody(string numeroRadicado) {
            this.numeroRadicado = numeroRadicado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerResumenRadicadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerResumenRadicadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoResponseBody Body;
        
        public ObtenerResumenRadicadoResponse() {
        }
        
        public ObtenerResumenRadicadoResponse(carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerResumenRadicadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public carEVA.sidcarUserServiceReference.ResumenRadicado ObtenerResumenRadicadoResult;
        
        public ObtenerResumenRadicadoResponseBody() {
        }
        
        public ObtenerResumenRadicadoResponseBody(carEVA.sidcarUserServiceReference.ResumenRadicado ObtenerResumenRadicadoResult) {
            this.ObtenerResumenRadicadoResult = ObtenerResumenRadicadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerResumenDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerResumenDocumento", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoRequestBody Body;
        
        public ObtenerResumenDocumentoRequest() {
        }
        
        public ObtenerResumenDocumentoRequest(carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerResumenDocumentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idDocumento;
        
        public ObtenerResumenDocumentoRequestBody() {
        }
        
        public ObtenerResumenDocumentoRequestBody(int idDocumento) {
            this.idDocumento = idDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerResumenDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerResumenDocumentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoResponseBody Body;
        
        public ObtenerResumenDocumentoResponse() {
        }
        
        public ObtenerResumenDocumentoResponse(carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerResumenDocumentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public carEVA.sidcarUserServiceReference.ResumenDocumento ObtenerResumenDocumentoResult;
        
        public ObtenerResumenDocumentoResponseBody() {
        }
        
        public ObtenerResumenDocumentoResponseBody(carEVA.sidcarUserServiceReference.ResumenDocumento ObtenerResumenDocumentoResult) {
            this.ObtenerResumenDocumentoResult = ObtenerResumenDocumentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AsociarRadicadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AsociarRadicado", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.AsociarRadicadoRequestBody Body;
        
        public AsociarRadicadoRequest() {
        }
        
        public AsociarRadicadoRequest(carEVA.Test.sidcarUserServiceReference.AsociarRadicadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AsociarRadicadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idOrigenSistema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numeroRadicado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string identificador;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int anioIdentificador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tipoIdentificador;
        
        public AsociarRadicadoRequestBody() {
        }
        
        public AsociarRadicadoRequestBody(string idOrigenSistema, string numeroRadicado, string identificador, int anioIdentificador, string tipoIdentificador) {
            this.idOrigenSistema = idOrigenSistema;
            this.numeroRadicado = numeroRadicado;
            this.identificador = identificador;
            this.anioIdentificador = anioIdentificador;
            this.tipoIdentificador = tipoIdentificador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AsociarRadicadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AsociarRadicadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.AsociarRadicadoResponseBody Body;
        
        public AsociarRadicadoResponse() {
        }
        
        public AsociarRadicadoResponse(carEVA.Test.sidcarUserServiceReference.AsociarRadicadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AsociarRadicadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AsociarRadicadoResult;
        
        public AsociarRadicadoResponseBody() {
        }
        
        public AsociarRadicadoResponseBody(string AsociarRadicadoResult) {
            this.AsociarRadicadoResult = AsociarRadicadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarRadicadoAsociadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarRadicadoAsociado", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoRequestBody Body;
        
        public EliminarRadicadoAsociadoRequest() {
        }
        
        public EliminarRadicadoAsociadoRequest(carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarRadicadoAsociadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idOrigenSistema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numeroRadicado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string identificador;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int anioIdentificador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tipoIdentificador;
        
        public EliminarRadicadoAsociadoRequestBody() {
        }
        
        public EliminarRadicadoAsociadoRequestBody(string idOrigenSistema, string numeroRadicado, string identificador, int anioIdentificador, string tipoIdentificador) {
            this.idOrigenSistema = idOrigenSistema;
            this.numeroRadicado = numeroRadicado;
            this.identificador = identificador;
            this.anioIdentificador = anioIdentificador;
            this.tipoIdentificador = tipoIdentificador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarRadicadoAsociadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarRadicadoAsociadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoResponseBody Body;
        
        public EliminarRadicadoAsociadoResponse() {
        }
        
        public EliminarRadicadoAsociadoResponse(carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarRadicadoAsociadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarRadicadoAsociadoResult;
        
        public EliminarRadicadoAsociadoResponseBody() {
        }
        
        public EliminarRadicadoAsociadoResponseBody(string EliminarRadicadoAsociadoResult) {
            this.EliminarRadicadoAsociadoResult = EliminarRadicadoAsociadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarDestinosDocumentoDigitalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarDestinosDocumentoDigital", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequestBody Body;
        
        public AgregarDestinosDocumentoDigitalRequest() {
        }
        
        public AgregarDestinosDocumentoDigitalRequest(carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarDestinosDocumentoDigitalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idSistemaOrigen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlDestinos;
        
        public AgregarDestinosDocumentoDigitalRequestBody() {
        }
        
        public AgregarDestinosDocumentoDigitalRequestBody(string idSistemaOrigen, string xmlDestinos) {
            this.idSistemaOrigen = idSistemaOrigen;
            this.xmlDestinos = xmlDestinos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarDestinosDocumentoDigitalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarDestinosDocumentoDigitalResponse", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponseBody Body;
        
        public AgregarDestinosDocumentoDigitalResponse() {
        }
        
        public AgregarDestinosDocumentoDigitalResponse(carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarDestinosDocumentoDigitalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgregarDestinosDocumentoDigitalResult;
        
        public AgregarDestinosDocumentoDigitalResponseBody() {
        }
        
        public AgregarDestinosDocumentoDigitalResponseBody(string AgregarDestinosDocumentoDigitalResult) {
            this.AgregarDestinosDocumentoDigitalResult = AgregarDestinosDocumentoDigitalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarDestinosDocumentoDigital2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarDestinosDocumentoDigital2", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2RequestBody Body;
        
        public AgregarDestinosDocumentoDigital2Request() {
        }
        
        public AgregarDestinosDocumentoDigital2Request(carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarDestinosDocumentoDigital2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idSistemaOrigen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.Linq.XElement xmlDestinos;
        
        public AgregarDestinosDocumentoDigital2RequestBody() {
        }
        
        public AgregarDestinosDocumentoDigital2RequestBody(string idSistemaOrigen, System.Xml.Linq.XElement xmlDestinos) {
            this.idSistemaOrigen = idSistemaOrigen;
            this.xmlDestinos = xmlDestinos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarDestinosDocumentoDigital2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarDestinosDocumentoDigital2Response", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2ResponseBody Body;
        
        public AgregarDestinosDocumentoDigital2Response() {
        }
        
        public AgregarDestinosDocumentoDigital2Response(carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarDestinosDocumentoDigital2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgregarDestinosDocumentoDigital2Result;
        
        public AgregarDestinosDocumentoDigital2ResponseBody() {
        }
        
        public AgregarDestinosDocumentoDigital2ResponseBody(string AgregarDestinosDocumentoDigital2Result) {
            this.AgregarDestinosDocumentoDigital2Result = AgregarDestinosDocumentoDigital2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignInJson", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.SignInJsonRequestBody Body;
        
        public SignInJsonRequest() {
        }
        
        public SignInJsonRequest(carEVA.Test.sidcarUserServiceReference.SignInJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idSistemaOrigen;
        
        public SignInJsonRequestBody() {
        }
        
        public SignInJsonRequestBody(string login, string password, string idSistemaOrigen) {
            this.login = login;
            this.password = password;
            this.idSistemaOrigen = idSistemaOrigen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignInJsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.SignInJsonResponseBody Body;
        
        public SignInJsonResponse() {
        }
        
        public SignInJsonResponse(carEVA.Test.sidcarUserServiceReference.SignInJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SignInJsonResult;
        
        public SignInJsonResponseBody() {
        }
        
        public SignInJsonResponseBody(string SignInJsonResult) {
            this.SignInJsonResult = SignInJsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaOficinasActivasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaOficinasActivas", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasRequestBody Body;
        
        public ListaOficinasActivasRequest() {
        }
        
        public ListaOficinasActivasRequest(carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaOficinasActivasRequestBody {
        
        public ListaOficinasActivasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaOficinasActivasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaOficinasActivasResponse", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasResponseBody Body;
        
        public ListaOficinasActivasResponse() {
        }
        
        public ListaOficinasActivasResponse(carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaOficinasActivasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListaOficinasActivasResult;
        
        public ListaOficinasActivasResponseBody() {
        }
        
        public ListaOficinasActivasResponseBody(string ListaOficinasActivasResult) {
            this.ListaOficinasActivasResult = ListaOficinasActivasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignIn", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.SignInRequestBody Body;
        
        public SignInRequest() {
        }
        
        public SignInRequest(carEVA.Test.sidcarUserServiceReference.SignInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public SignInRequestBody() {
        }
        
        public SignInRequestBody(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignInResponse", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.Test.sidcarUserServiceReference.SignInResponseBody Body;
        
        public SignInResponse() {
        }
        
        public SignInResponse(carEVA.Test.sidcarUserServiceReference.SignInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public carEVA.Test.sidcarUserServiceReference.WSUsuario SignInResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensajeWSError;
        
        public SignInResponseBody() {
        }
        
        public SignInResponseBody(carEVA.Test.sidcarUserServiceReference.WSUsuario SignInResult, string mensajeWSError) {
            this.SignInResult = SignInResult;
            this.mensajeWSError = mensajeWSError;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSIntegracionSoapChannel : carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSIntegracionSoapClient : System.ServiceModel.ClientBase<carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap>, carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap {
        
        public WSIntegracionSoapClient() {
        }
        
        public WSIntegracionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSIntegracionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSIntegracionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSIntegracionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoResponse carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.ObtenerResumenRadicado(carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoRequest request) {
            return base.Channel.ObtenerResumenRadicado(request);
        }
        
        public carEVA.sidcarUserServiceReference.ResumenRadicado ObtenerResumenRadicado(string numeroRadicado) {
            carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoRequest inValue = new carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoRequestBody();
            inValue.Body.numeroRadicado = numeroRadicado;
            carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoResponse retVal = ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).ObtenerResumenRadicado(inValue);
            return retVal.Body.ObtenerResumenRadicadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoResponse> carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.ObtenerResumenRadicadoAsync(carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoRequest request) {
            return base.Channel.ObtenerResumenRadicadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoResponse> ObtenerResumenRadicadoAsync(string numeroRadicado) {
            carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoRequest inValue = new carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.ObtenerResumenRadicadoRequestBody();
            inValue.Body.numeroRadicado = numeroRadicado;
            return ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).ObtenerResumenRadicadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoResponse carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.ObtenerResumenDocumento(carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoRequest request) {
            return base.Channel.ObtenerResumenDocumento(request);
        }
        
        public carEVA.sidcarUserServiceReference.ResumenDocumento ObtenerResumenDocumento(int idDocumento) {
            carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoRequest inValue = new carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoRequestBody();
            inValue.Body.idDocumento = idDocumento;
            carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoResponse retVal = ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).ObtenerResumenDocumento(inValue);
            return retVal.Body.ObtenerResumenDocumentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoResponse> carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.ObtenerResumenDocumentoAsync(carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoRequest request) {
            return base.Channel.ObtenerResumenDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoResponse> ObtenerResumenDocumentoAsync(int idDocumento) {
            carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoRequest inValue = new carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.ObtenerResumenDocumentoRequestBody();
            inValue.Body.idDocumento = idDocumento;
            return ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).ObtenerResumenDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        carEVA.Test.sidcarUserServiceReference.AsociarRadicadoResponse carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.AsociarRadicado(carEVA.Test.sidcarUserServiceReference.AsociarRadicadoRequest request) {
            return base.Channel.AsociarRadicado(request);
        }
        
        public string AsociarRadicado(string idOrigenSistema, string numeroRadicado, string identificador, int anioIdentificador, string tipoIdentificador) {
            carEVA.Test.sidcarUserServiceReference.AsociarRadicadoRequest inValue = new carEVA.Test.sidcarUserServiceReference.AsociarRadicadoRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.AsociarRadicadoRequestBody();
            inValue.Body.idOrigenSistema = idOrigenSistema;
            inValue.Body.numeroRadicado = numeroRadicado;
            inValue.Body.identificador = identificador;
            inValue.Body.anioIdentificador = anioIdentificador;
            inValue.Body.tipoIdentificador = tipoIdentificador;
            carEVA.Test.sidcarUserServiceReference.AsociarRadicadoResponse retVal = ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).AsociarRadicado(inValue);
            return retVal.Body.AsociarRadicadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.AsociarRadicadoResponse> carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.AsociarRadicadoAsync(carEVA.Test.sidcarUserServiceReference.AsociarRadicadoRequest request) {
            return base.Channel.AsociarRadicadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.AsociarRadicadoResponse> AsociarRadicadoAsync(string idOrigenSistema, string numeroRadicado, string identificador, int anioIdentificador, string tipoIdentificador) {
            carEVA.Test.sidcarUserServiceReference.AsociarRadicadoRequest inValue = new carEVA.Test.sidcarUserServiceReference.AsociarRadicadoRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.AsociarRadicadoRequestBody();
            inValue.Body.idOrigenSistema = idOrigenSistema;
            inValue.Body.numeroRadicado = numeroRadicado;
            inValue.Body.identificador = identificador;
            inValue.Body.anioIdentificador = anioIdentificador;
            inValue.Body.tipoIdentificador = tipoIdentificador;
            return ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).AsociarRadicadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoResponse carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.EliminarRadicadoAsociado(carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoRequest request) {
            return base.Channel.EliminarRadicadoAsociado(request);
        }
        
        public string EliminarRadicadoAsociado(string idOrigenSistema, string numeroRadicado, string identificador, int anioIdentificador, string tipoIdentificador) {
            carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoRequest inValue = new carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoRequestBody();
            inValue.Body.idOrigenSistema = idOrigenSistema;
            inValue.Body.numeroRadicado = numeroRadicado;
            inValue.Body.identificador = identificador;
            inValue.Body.anioIdentificador = anioIdentificador;
            inValue.Body.tipoIdentificador = tipoIdentificador;
            carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoResponse retVal = ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).EliminarRadicadoAsociado(inValue);
            return retVal.Body.EliminarRadicadoAsociadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoResponse> carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.EliminarRadicadoAsociadoAsync(carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoRequest request) {
            return base.Channel.EliminarRadicadoAsociadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoResponse> EliminarRadicadoAsociadoAsync(string idOrigenSistema, string numeroRadicado, string identificador, int anioIdentificador, string tipoIdentificador) {
            carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoRequest inValue = new carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.EliminarRadicadoAsociadoRequestBody();
            inValue.Body.idOrigenSistema = idOrigenSistema;
            inValue.Body.numeroRadicado = numeroRadicado;
            inValue.Body.identificador = identificador;
            inValue.Body.anioIdentificador = anioIdentificador;
            inValue.Body.tipoIdentificador = tipoIdentificador;
            return ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).EliminarRadicadoAsociadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponse carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.AgregarDestinosDocumentoDigital(carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest request) {
            return base.Channel.AgregarDestinosDocumentoDigital(request);
        }
        
        public string AgregarDestinosDocumentoDigital(string idSistemaOrigen, string xmlDestinos) {
            carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest inValue = new carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequestBody();
            inValue.Body.idSistemaOrigen = idSistemaOrigen;
            inValue.Body.xmlDestinos = xmlDestinos;
            carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponse retVal = ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).AgregarDestinosDocumentoDigital(inValue);
            return retVal.Body.AgregarDestinosDocumentoDigitalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponse> carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.AgregarDestinosDocumentoDigitalAsync(carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest request) {
            return base.Channel.AgregarDestinosDocumentoDigitalAsync(request);
        }
        
        public System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponse> AgregarDestinosDocumentoDigitalAsync(string idSistemaOrigen, string xmlDestinos) {
            carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest inValue = new carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequestBody();
            inValue.Body.idSistemaOrigen = idSistemaOrigen;
            inValue.Body.xmlDestinos = xmlDestinos;
            return ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).AgregarDestinosDocumentoDigitalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Response carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.AgregarDestinosDocumentoDigital2(carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request request) {
            return base.Channel.AgregarDestinosDocumentoDigital2(request);
        }
        
        public string AgregarDestinosDocumentoDigital2(string idSistemaOrigen, System.Xml.Linq.XElement xmlDestinos) {
            carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request inValue = new carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2RequestBody();
            inValue.Body.idSistemaOrigen = idSistemaOrigen;
            inValue.Body.xmlDestinos = xmlDestinos;
            carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Response retVal = ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).AgregarDestinosDocumentoDigital2(inValue);
            return retVal.Body.AgregarDestinosDocumentoDigital2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Response> carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.AgregarDestinosDocumentoDigital2Async(carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request request) {
            return base.Channel.AgregarDestinosDocumentoDigital2Async(request);
        }
        
        public System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Response> AgregarDestinosDocumentoDigital2Async(string idSistemaOrigen, System.Xml.Linq.XElement xmlDestinos) {
            carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request inValue = new carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2RequestBody();
            inValue.Body.idSistemaOrigen = idSistemaOrigen;
            inValue.Body.xmlDestinos = xmlDestinos;
            return ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).AgregarDestinosDocumentoDigital2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        carEVA.Test.sidcarUserServiceReference.SignInJsonResponse carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.SignInJson(carEVA.Test.sidcarUserServiceReference.SignInJsonRequest request) {
            return base.Channel.SignInJson(request);
        }
        
        public string SignInJson(string login, string password, string idSistemaOrigen) {
            carEVA.Test.sidcarUserServiceReference.SignInJsonRequest inValue = new carEVA.Test.sidcarUserServiceReference.SignInJsonRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.SignInJsonRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.idSistemaOrigen = idSistemaOrigen;
            carEVA.Test.sidcarUserServiceReference.SignInJsonResponse retVal = ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).SignInJson(inValue);
            return retVal.Body.SignInJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.SignInJsonResponse> carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.SignInJsonAsync(carEVA.Test.sidcarUserServiceReference.SignInJsonRequest request) {
            return base.Channel.SignInJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.SignInJsonResponse> SignInJsonAsync(string login, string password, string idSistemaOrigen) {
            carEVA.Test.sidcarUserServiceReference.SignInJsonRequest inValue = new carEVA.Test.sidcarUserServiceReference.SignInJsonRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.SignInJsonRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.idSistemaOrigen = idSistemaOrigen;
            return ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).SignInJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasResponse carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.ListaOficinasActivas(carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasRequest request) {
            return base.Channel.ListaOficinasActivas(request);
        }
        
        public string ListaOficinasActivas() {
            carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasRequest inValue = new carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasRequestBody();
            carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasResponse retVal = ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).ListaOficinasActivas(inValue);
            return retVal.Body.ListaOficinasActivasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasResponse> carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.ListaOficinasActivasAsync(carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasRequest request) {
            return base.Channel.ListaOficinasActivasAsync(request);
        }
        
        public System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasResponse> ListaOficinasActivasAsync() {
            carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasRequest inValue = new carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.ListaOficinasActivasRequestBody();
            return ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).ListaOficinasActivasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        carEVA.Test.sidcarUserServiceReference.SignInResponse carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.SignIn(carEVA.Test.sidcarUserServiceReference.SignInRequest request) {
            return base.Channel.SignIn(request);
        }
        
        public carEVA.Test.sidcarUserServiceReference.WSUsuario SignIn(string login, string password, out string mensajeWSError) {
            carEVA.Test.sidcarUserServiceReference.SignInRequest inValue = new carEVA.Test.sidcarUserServiceReference.SignInRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.SignInRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            carEVA.Test.sidcarUserServiceReference.SignInResponse retVal = ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).SignIn(inValue);
            mensajeWSError = retVal.Body.mensajeWSError;
            return retVal.Body.SignInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.SignInResponse> carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap.SignInAsync(carEVA.Test.sidcarUserServiceReference.SignInRequest request) {
            return base.Channel.SignInAsync(request);
        }
        
        public System.Threading.Tasks.Task<carEVA.Test.sidcarUserServiceReference.SignInResponse> SignInAsync(string login, string password) {
            carEVA.Test.sidcarUserServiceReference.SignInRequest inValue = new carEVA.Test.sidcarUserServiceReference.SignInRequest();
            inValue.Body = new carEVA.Test.sidcarUserServiceReference.SignInRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            return ((carEVA.Test.sidcarUserServiceReference.WSIntegracionSoap)(this)).SignInAsync(inValue);
        }
    }
}
