//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carEVA.sidcarUserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResumenRadicado", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResumenRadicado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDRadicadoField;
        
        private System.DateTime FechaRadicadoField;
        
        private byte IDTipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TramiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemitenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VeredaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OficinaRadicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlPDFField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IDRadicado {
            get {
                return this.IDRadicadoField;
            }
            set {
                if ((this.IDRadicadoField.Equals(value) != true)) {
                    this.IDRadicadoField = value;
                    this.RaisePropertyChanged("IDRadicado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime FechaRadicado {
            get {
                return this.FechaRadicadoField;
            }
            set {
                if ((this.FechaRadicadoField.Equals(value) != true)) {
                    this.FechaRadicadoField = value;
                    this.RaisePropertyChanged("FechaRadicado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public byte IDTipoDocumento {
            get {
                return this.IDTipoDocumentoField;
            }
            set {
                if ((this.IDTipoDocumentoField.Equals(value) != true)) {
                    this.IDTipoDocumentoField = value;
                    this.RaisePropertyChanged("IDTipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Tramite {
            get {
                return this.TramiteField;
            }
            set {
                if ((object.ReferenceEquals(this.TramiteField, value) != true)) {
                    this.TramiteField = value;
                    this.RaisePropertyChanged("Tramite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Tema {
            get {
                return this.TemaField;
            }
            set {
                if ((object.ReferenceEquals(this.TemaField, value) != true)) {
                    this.TemaField = value;
                    this.RaisePropertyChanged("Tema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Remitente {
            get {
                return this.RemitenteField;
            }
            set {
                if ((object.ReferenceEquals(this.RemitenteField, value) != true)) {
                    this.RemitenteField = value;
                    this.RaisePropertyChanged("Remitente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Municipio {
            get {
                return this.MunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipioField, value) != true)) {
                    this.MunicipioField = value;
                    this.RaisePropertyChanged("Municipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Asunto {
            get {
                return this.AsuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.AsuntoField, value) != true)) {
                    this.AsuntoField = value;
                    this.RaisePropertyChanged("Asunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Entidad {
            get {
                return this.EntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadField, value) != true)) {
                    this.EntidadField = value;
                    this.RaisePropertyChanged("Entidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Vereda {
            get {
                return this.VeredaField;
            }
            set {
                if ((object.ReferenceEquals(this.VeredaField, value) != true)) {
                    this.VeredaField = value;
                    this.RaisePropertyChanged("Vereda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string OficinaRadica {
            get {
                return this.OficinaRadicaField;
            }
            set {
                if ((object.ReferenceEquals(this.OficinaRadicaField, value) != true)) {
                    this.OficinaRadicaField = value;
                    this.RaisePropertyChanged("OficinaRadica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string UrlPDF {
            get {
                return this.UrlPDFField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlPDFField, value) != true)) {
                    this.UrlPDFField = value;
                    this.RaisePropertyChanged("UrlPDF");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResumenDocumento", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResumenDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDDocumentoField;
        
        private byte IDTipoDocumentoField;
        
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinatariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OficinaElaboraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioElaboraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlPDFField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IDDocumento {
            get {
                return this.IDDocumentoField;
            }
            set {
                if ((this.IDDocumentoField.Equals(value) != true)) {
                    this.IDDocumentoField = value;
                    this.RaisePropertyChanged("IDDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte IDTipoDocumento {
            get {
                return this.IDTipoDocumentoField;
            }
            set {
                if ((this.IDTipoDocumentoField.Equals(value) != true)) {
                    this.IDTipoDocumentoField = value;
                    this.RaisePropertyChanged("IDTipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Asunto {
            get {
                return this.AsuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.AsuntoField, value) != true)) {
                    this.AsuntoField = value;
                    this.RaisePropertyChanged("Asunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Destinatarios {
            get {
                return this.DestinatariosField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinatariosField, value) != true)) {
                    this.DestinatariosField = value;
                    this.RaisePropertyChanged("Destinatarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string OficinaElabora {
            get {
                return this.OficinaElaboraField;
            }
            set {
                if ((object.ReferenceEquals(this.OficinaElaboraField, value) != true)) {
                    this.OficinaElaboraField = value;
                    this.RaisePropertyChanged("OficinaElabora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string UsuarioElabora {
            get {
                return this.UsuarioElaboraField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioElaboraField, value) != true)) {
                    this.UsuarioElaboraField = value;
                    this.RaisePropertyChanged("UsuarioElabora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string UrlPDF {
            get {
                return this.UrlPDFField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlPDFField, value) != true)) {
                    this.UrlPDFField = value;
                    this.RaisePropertyChanged("UrlPDF");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="sidcarUserServiceReference.WSIntegracionSoap")]
    public interface WSIntegracionSoap {
        
        // CODEGEN: Generating message contract since element name numeroRadicado from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerResumenRadicado", ReplyAction="*")]
        carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoResponse ObtenerResumenRadicado(carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerResumenRadicado", ReplyAction="*")]
        System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoResponse> ObtenerResumenRadicadoAsync(carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoRequest request);
        
        // CODEGEN: Generating message contract since element name ObtenerResumenDocumentoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerResumenDocumento", ReplyAction="*")]
        carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoResponse ObtenerResumenDocumento(carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerResumenDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoResponse> ObtenerResumenDocumentoAsync(carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoRequest request);
        
        // CODEGEN: Generating message contract since element name numeroRadicado from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AsociarRadicado", ReplyAction="*")]
        carEVA.sidcarUserServiceReference.AsociarRadicadoResponse AsociarRadicado(carEVA.sidcarUserServiceReference.AsociarRadicadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AsociarRadicado", ReplyAction="*")]
        System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.AsociarRadicadoResponse> AsociarRadicadoAsync(carEVA.sidcarUserServiceReference.AsociarRadicadoRequest request);
        
        // CODEGEN: Generating message contract since element name idSistemaOrigen from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarDestinosDocumentoDigital", ReplyAction="*")]
        carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponse AgregarDestinosDocumentoDigital(carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarDestinosDocumentoDigital", ReplyAction="*")]
        System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponse> AgregarDestinosDocumentoDigitalAsync(carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest request);
        
        // CODEGEN: Generating message contract since element name idSistemaOrigen from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarDestinosDocumentoDigital2", ReplyAction="*")]
        carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Response AgregarDestinosDocumentoDigital2(carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarDestinosDocumentoDigital2", ReplyAction="*")]
        System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Response> AgregarDestinosDocumentoDigital2Async(carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignInJson", ReplyAction="*")]
        carEVA.sidcarUserServiceReference.SignInJsonResponse SignInJson(carEVA.sidcarUserServiceReference.SignInJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignInJson", ReplyAction="*")]
        System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.SignInJsonResponse> SignInJsonAsync(carEVA.sidcarUserServiceReference.SignInJsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerResumenRadicadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerResumenRadicado", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoRequestBody Body;
        
        public ObtenerResumenRadicadoRequest() {
        }
        
        public ObtenerResumenRadicadoRequest(carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerResumenRadicadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroRadicado;
        
        public ObtenerResumenRadicadoRequestBody() {
        }
        
        public ObtenerResumenRadicadoRequestBody(string numeroRadicado) {
            this.numeroRadicado = numeroRadicado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerResumenRadicadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerResumenRadicadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoResponseBody Body;
        
        public ObtenerResumenRadicadoResponse() {
        }
        
        public ObtenerResumenRadicadoResponse(carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerResumenRadicadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public carEVA.sidcarUserServiceReference.ResumenRadicado ObtenerResumenRadicadoResult;
        
        public ObtenerResumenRadicadoResponseBody() {
        }
        
        public ObtenerResumenRadicadoResponseBody(carEVA.sidcarUserServiceReference.ResumenRadicado ObtenerResumenRadicadoResult) {
            this.ObtenerResumenRadicadoResult = ObtenerResumenRadicadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerResumenDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerResumenDocumento", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoRequestBody Body;
        
        public ObtenerResumenDocumentoRequest() {
        }
        
        public ObtenerResumenDocumentoRequest(carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerResumenDocumentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idDocumento;
        
        public ObtenerResumenDocumentoRequestBody() {
        }
        
        public ObtenerResumenDocumentoRequestBody(int idDocumento) {
            this.idDocumento = idDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerResumenDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerResumenDocumentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoResponseBody Body;
        
        public ObtenerResumenDocumentoResponse() {
        }
        
        public ObtenerResumenDocumentoResponse(carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerResumenDocumentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public carEVA.sidcarUserServiceReference.ResumenDocumento ObtenerResumenDocumentoResult;
        
        public ObtenerResumenDocumentoResponseBody() {
        }
        
        public ObtenerResumenDocumentoResponseBody(carEVA.sidcarUserServiceReference.ResumenDocumento ObtenerResumenDocumentoResult) {
            this.ObtenerResumenDocumentoResult = ObtenerResumenDocumentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AsociarRadicadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AsociarRadicado", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.sidcarUserServiceReference.AsociarRadicadoRequestBody Body;
        
        public AsociarRadicadoRequest() {
        }
        
        public AsociarRadicadoRequest(carEVA.sidcarUserServiceReference.AsociarRadicadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AsociarRadicadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroRadicado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string valorID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idOrigenSistema;
        
        public AsociarRadicadoRequestBody() {
        }
        
        public AsociarRadicadoRequestBody(string numeroRadicado, string valorID, string idOrigenSistema) {
            this.numeroRadicado = numeroRadicado;
            this.valorID = valorID;
            this.idOrigenSistema = idOrigenSistema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AsociarRadicadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AsociarRadicadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.sidcarUserServiceReference.AsociarRadicadoResponseBody Body;
        
        public AsociarRadicadoResponse() {
        }
        
        public AsociarRadicadoResponse(carEVA.sidcarUserServiceReference.AsociarRadicadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AsociarRadicadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AsociarRadicadoResult;
        
        public AsociarRadicadoResponseBody() {
        }
        
        public AsociarRadicadoResponseBody(string AsociarRadicadoResult) {
            this.AsociarRadicadoResult = AsociarRadicadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarDestinosDocumentoDigitalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarDestinosDocumentoDigital", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequestBody Body;
        
        public AgregarDestinosDocumentoDigitalRequest() {
        }
        
        public AgregarDestinosDocumentoDigitalRequest(carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarDestinosDocumentoDigitalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idSistemaOrigen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlDestinos;
        
        public AgregarDestinosDocumentoDigitalRequestBody() {
        }
        
        public AgregarDestinosDocumentoDigitalRequestBody(string idSistemaOrigen, string xmlDestinos) {
            this.idSistemaOrigen = idSistemaOrigen;
            this.xmlDestinos = xmlDestinos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarDestinosDocumentoDigitalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarDestinosDocumentoDigitalResponse", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponseBody Body;
        
        public AgregarDestinosDocumentoDigitalResponse() {
        }
        
        public AgregarDestinosDocumentoDigitalResponse(carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarDestinosDocumentoDigitalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgregarDestinosDocumentoDigitalResult;
        
        public AgregarDestinosDocumentoDigitalResponseBody() {
        }
        
        public AgregarDestinosDocumentoDigitalResponseBody(string AgregarDestinosDocumentoDigitalResult) {
            this.AgregarDestinosDocumentoDigitalResult = AgregarDestinosDocumentoDigitalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarDestinosDocumentoDigital2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarDestinosDocumentoDigital2", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2RequestBody Body;
        
        public AgregarDestinosDocumentoDigital2Request() {
        }
        
        public AgregarDestinosDocumentoDigital2Request(carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarDestinosDocumentoDigital2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idSistemaOrigen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.Linq.XElement xmlDestinos;
        
        public AgregarDestinosDocumentoDigital2RequestBody() {
        }
        
        public AgregarDestinosDocumentoDigital2RequestBody(string idSistemaOrigen, System.Xml.Linq.XElement xmlDestinos) {
            this.idSistemaOrigen = idSistemaOrigen;
            this.xmlDestinos = xmlDestinos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarDestinosDocumentoDigital2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarDestinosDocumentoDigital2Response", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2ResponseBody Body;
        
        public AgregarDestinosDocumentoDigital2Response() {
        }
        
        public AgregarDestinosDocumentoDigital2Response(carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarDestinosDocumentoDigital2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgregarDestinosDocumentoDigital2Result;
        
        public AgregarDestinosDocumentoDigital2ResponseBody() {
        }
        
        public AgregarDestinosDocumentoDigital2ResponseBody(string AgregarDestinosDocumentoDigital2Result) {
            this.AgregarDestinosDocumentoDigital2Result = AgregarDestinosDocumentoDigital2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignInJson", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.sidcarUserServiceReference.SignInJsonRequestBody Body;
        
        public SignInJsonRequest() {
        }
        
        public SignInJsonRequest(carEVA.sidcarUserServiceReference.SignInJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idSistemaOrigen;
        
        public SignInJsonRequestBody() {
        }
        
        public SignInJsonRequestBody(string login, string password, string idSistemaOrigen) {
            this.login = login;
            this.password = password;
            this.idSistemaOrigen = idSistemaOrigen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignInJsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public carEVA.sidcarUserServiceReference.SignInJsonResponseBody Body;
        
        public SignInJsonResponse() {
        }
        
        public SignInJsonResponse(carEVA.sidcarUserServiceReference.SignInJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SignInJsonResult;
        
        public SignInJsonResponseBody() {
        }
        
        public SignInJsonResponseBody(string SignInJsonResult) {
            this.SignInJsonResult = SignInJsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSIntegracionSoapChannel : carEVA.sidcarUserServiceReference.WSIntegracionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSIntegracionSoapClient : System.ServiceModel.ClientBase<carEVA.sidcarUserServiceReference.WSIntegracionSoap>, carEVA.sidcarUserServiceReference.WSIntegracionSoap {
        
        public WSIntegracionSoapClient() {
        }
        
        public WSIntegracionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSIntegracionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSIntegracionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSIntegracionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoResponse carEVA.sidcarUserServiceReference.WSIntegracionSoap.ObtenerResumenRadicado(carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoRequest request) {
            return base.Channel.ObtenerResumenRadicado(request);
        }
        
        public carEVA.sidcarUserServiceReference.ResumenRadicado ObtenerResumenRadicado(string numeroRadicado) {
            carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoRequest inValue = new carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoRequest();
            inValue.Body = new carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoRequestBody();
            inValue.Body.numeroRadicado = numeroRadicado;
            carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoResponse retVal = ((carEVA.sidcarUserServiceReference.WSIntegracionSoap)(this)).ObtenerResumenRadicado(inValue);
            return retVal.Body.ObtenerResumenRadicadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoResponse> carEVA.sidcarUserServiceReference.WSIntegracionSoap.ObtenerResumenRadicadoAsync(carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoRequest request) {
            return base.Channel.ObtenerResumenRadicadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoResponse> ObtenerResumenRadicadoAsync(string numeroRadicado) {
            carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoRequest inValue = new carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoRequest();
            inValue.Body = new carEVA.sidcarUserServiceReference.ObtenerResumenRadicadoRequestBody();
            inValue.Body.numeroRadicado = numeroRadicado;
            return ((carEVA.sidcarUserServiceReference.WSIntegracionSoap)(this)).ObtenerResumenRadicadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoResponse carEVA.sidcarUserServiceReference.WSIntegracionSoap.ObtenerResumenDocumento(carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoRequest request) {
            return base.Channel.ObtenerResumenDocumento(request);
        }
        
        public carEVA.sidcarUserServiceReference.ResumenDocumento ObtenerResumenDocumento(int idDocumento) {
            carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoRequest inValue = new carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoRequest();
            inValue.Body = new carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoRequestBody();
            inValue.Body.idDocumento = idDocumento;
            carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoResponse retVal = ((carEVA.sidcarUserServiceReference.WSIntegracionSoap)(this)).ObtenerResumenDocumento(inValue);
            return retVal.Body.ObtenerResumenDocumentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoResponse> carEVA.sidcarUserServiceReference.WSIntegracionSoap.ObtenerResumenDocumentoAsync(carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoRequest request) {
            return base.Channel.ObtenerResumenDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoResponse> ObtenerResumenDocumentoAsync(int idDocumento) {
            carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoRequest inValue = new carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoRequest();
            inValue.Body = new carEVA.sidcarUserServiceReference.ObtenerResumenDocumentoRequestBody();
            inValue.Body.idDocumento = idDocumento;
            return ((carEVA.sidcarUserServiceReference.WSIntegracionSoap)(this)).ObtenerResumenDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        carEVA.sidcarUserServiceReference.AsociarRadicadoResponse carEVA.sidcarUserServiceReference.WSIntegracionSoap.AsociarRadicado(carEVA.sidcarUserServiceReference.AsociarRadicadoRequest request) {
            return base.Channel.AsociarRadicado(request);
        }
        
        public string AsociarRadicado(string numeroRadicado, string valorID, string idOrigenSistema) {
            carEVA.sidcarUserServiceReference.AsociarRadicadoRequest inValue = new carEVA.sidcarUserServiceReference.AsociarRadicadoRequest();
            inValue.Body = new carEVA.sidcarUserServiceReference.AsociarRadicadoRequestBody();
            inValue.Body.numeroRadicado = numeroRadicado;
            inValue.Body.valorID = valorID;
            inValue.Body.idOrigenSistema = idOrigenSistema;
            carEVA.sidcarUserServiceReference.AsociarRadicadoResponse retVal = ((carEVA.sidcarUserServiceReference.WSIntegracionSoap)(this)).AsociarRadicado(inValue);
            return retVal.Body.AsociarRadicadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.AsociarRadicadoResponse> carEVA.sidcarUserServiceReference.WSIntegracionSoap.AsociarRadicadoAsync(carEVA.sidcarUserServiceReference.AsociarRadicadoRequest request) {
            return base.Channel.AsociarRadicadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.AsociarRadicadoResponse> AsociarRadicadoAsync(string numeroRadicado, string valorID, string idOrigenSistema) {
            carEVA.sidcarUserServiceReference.AsociarRadicadoRequest inValue = new carEVA.sidcarUserServiceReference.AsociarRadicadoRequest();
            inValue.Body = new carEVA.sidcarUserServiceReference.AsociarRadicadoRequestBody();
            inValue.Body.numeroRadicado = numeroRadicado;
            inValue.Body.valorID = valorID;
            inValue.Body.idOrigenSistema = idOrigenSistema;
            return ((carEVA.sidcarUserServiceReference.WSIntegracionSoap)(this)).AsociarRadicadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponse carEVA.sidcarUserServiceReference.WSIntegracionSoap.AgregarDestinosDocumentoDigital(carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest request) {
            return base.Channel.AgregarDestinosDocumentoDigital(request);
        }
        
        public string AgregarDestinosDocumentoDigital(string idSistemaOrigen, string xmlDestinos) {
            carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest inValue = new carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest();
            inValue.Body = new carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequestBody();
            inValue.Body.idSistemaOrigen = idSistemaOrigen;
            inValue.Body.xmlDestinos = xmlDestinos;
            carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponse retVal = ((carEVA.sidcarUserServiceReference.WSIntegracionSoap)(this)).AgregarDestinosDocumentoDigital(inValue);
            return retVal.Body.AgregarDestinosDocumentoDigitalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponse> carEVA.sidcarUserServiceReference.WSIntegracionSoap.AgregarDestinosDocumentoDigitalAsync(carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest request) {
            return base.Channel.AgregarDestinosDocumentoDigitalAsync(request);
        }
        
        public System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalResponse> AgregarDestinosDocumentoDigitalAsync(string idSistemaOrigen, string xmlDestinos) {
            carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest inValue = new carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequest();
            inValue.Body = new carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigitalRequestBody();
            inValue.Body.idSistemaOrigen = idSistemaOrigen;
            inValue.Body.xmlDestinos = xmlDestinos;
            return ((carEVA.sidcarUserServiceReference.WSIntegracionSoap)(this)).AgregarDestinosDocumentoDigitalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Response carEVA.sidcarUserServiceReference.WSIntegracionSoap.AgregarDestinosDocumentoDigital2(carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request request) {
            return base.Channel.AgregarDestinosDocumentoDigital2(request);
        }
        
        public string AgregarDestinosDocumentoDigital2(string idSistemaOrigen, System.Xml.Linq.XElement xmlDestinos) {
            carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request inValue = new carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request();
            inValue.Body = new carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2RequestBody();
            inValue.Body.idSistemaOrigen = idSistemaOrigen;
            inValue.Body.xmlDestinos = xmlDestinos;
            carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Response retVal = ((carEVA.sidcarUserServiceReference.WSIntegracionSoap)(this)).AgregarDestinosDocumentoDigital2(inValue);
            return retVal.Body.AgregarDestinosDocumentoDigital2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Response> carEVA.sidcarUserServiceReference.WSIntegracionSoap.AgregarDestinosDocumentoDigital2Async(carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request request) {
            return base.Channel.AgregarDestinosDocumentoDigital2Async(request);
        }
        
        public System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Response> AgregarDestinosDocumentoDigital2Async(string idSistemaOrigen, System.Xml.Linq.XElement xmlDestinos) {
            carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request inValue = new carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2Request();
            inValue.Body = new carEVA.sidcarUserServiceReference.AgregarDestinosDocumentoDigital2RequestBody();
            inValue.Body.idSistemaOrigen = idSistemaOrigen;
            inValue.Body.xmlDestinos = xmlDestinos;
            return ((carEVA.sidcarUserServiceReference.WSIntegracionSoap)(this)).AgregarDestinosDocumentoDigital2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        carEVA.sidcarUserServiceReference.SignInJsonResponse carEVA.sidcarUserServiceReference.WSIntegracionSoap.SignInJson(carEVA.sidcarUserServiceReference.SignInJsonRequest request) {
            return base.Channel.SignInJson(request);
        }
        
        public string SignInJson(string login, string password, string idSistemaOrigen) {
            carEVA.sidcarUserServiceReference.SignInJsonRequest inValue = new carEVA.sidcarUserServiceReference.SignInJsonRequest();
            inValue.Body = new carEVA.sidcarUserServiceReference.SignInJsonRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.idSistemaOrigen = idSistemaOrigen;
            carEVA.sidcarUserServiceReference.SignInJsonResponse retVal = ((carEVA.sidcarUserServiceReference.WSIntegracionSoap)(this)).SignInJson(inValue);
            return retVal.Body.SignInJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.SignInJsonResponse> carEVA.sidcarUserServiceReference.WSIntegracionSoap.SignInJsonAsync(carEVA.sidcarUserServiceReference.SignInJsonRequest request) {
            return base.Channel.SignInJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<carEVA.sidcarUserServiceReference.SignInJsonResponse> SignInJsonAsync(string login, string password, string idSistemaOrigen) {
            carEVA.sidcarUserServiceReference.SignInJsonRequest inValue = new carEVA.sidcarUserServiceReference.SignInJsonRequest();
            inValue.Body = new carEVA.sidcarUserServiceReference.SignInJsonRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.idSistemaOrigen = idSistemaOrigen;
            return ((carEVA.sidcarUserServiceReference.WSIntegracionSoap)(this)).SignInJsonAsync(inValue);
        }
    }
}
